---
#- name: Add neo4j key
#  apt_key:
#    url: http://debian.neo4j.org/neotechnology.gpg.key
#    state: present

- name: add neo4j apt_key
  apt_key:
    url: https://debian.neo4j.org/neotechnology.gpg.key
    state: present

- name: repo
  apt_repository:
    repo: 'deb http://debian.neo4j.org/repo stable/'
    state: present
    filename: neo4j-enterprise

- name: install_neo4j
  apt:
    name: neo4j=2.3.12
    state: present

- template:
    src: neo4j.properties.j2
    dest: /etc/neo4j/neo4j.properties
    owner: neo4j
    group: adm
    mode: 0644

- template:
    src: neo4j.j2
    dest: /etc/default/neo4j
    owner: root
    group: root
    mode: 0644

- name: restart_neo4j
  service:
    name: neo4j
    state: restarted
