---
- name: Configure servers with ruby support system wide
  hosts: all
  become: true
  roles:
    - { role: rvm.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.3.1'],
        rvm1_install_flags: '--user-install',
        rvm1_install_path: '~/.rvm',
        rvm1_bundler_install: True,
        rvm1_user: 'vagrant',
        rvm1_autolib_mode: 3
     }
    - { role: general }
    - { role: memcached }
    - { role: neo4j }
    - { role: pdftk }
    - { role: postgresql }
