---
- name: sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%admin'
    line: '%admin ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Create Users
  user: name={{ item.username }} comment="{{ item.username }}"
    groups=admin, append=yes
  with_items:
    - "{{ ssh_users }}"

- name: authuser
  authorized_key: user={{ item.username }} key="{{ item.key }}"
  with_items:
    - "{{ ssh_users }}"
