- name: add new4j apt_key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: repo
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main'
    state: present
    filename: pgdg

- name: install_libpq_dev
  apt:
    name: libpq-dev
    state: present

- name: install_postgresql_contrib
  apt:
    name: postgresql-contrib
    state: present

- name: install_postgresql
  apt:
    name: postgresql-9.6
    state: present
